### ISSUE TITLE
explicit convert make an overflow, make dequeueBatch broken

### ISSUE THREAD

**Issue by lust4life** [logary/RingBuffer#2]
https://github.com/logary/RingBuffer/blob/master/RingBuffer.fs#L51-L52

```fsharp
    let takeBatch (maxBatchSize : uint32) q = q.takeBatchCh *<-=>- (fun iv -> int maxBatchSize, iv)
    let takeAll q = takeBatch System.UInt32.MaxValue q
```

maybe some overflow make an array create exception. here we explicit convert `uint.MaxValue` to `int`, seems get an overflow , so here the `dequeueCount`  get **-1** , make array create argument exception.

```fsharp
    let dequeueBatch (max, ivar) =
    let dequeueCount = min max <| count ()
    let arr = Array.zeroCreate dequeueCount
```

maybe use  `System.UInt16.MaxValue` and uint16 ?

if change, maybe broken here : https://github.com/logary/logary/blob/master/src/Logary/Targets_Core.fs#L1406

**Comment by haf** [comment]
Well spotted. I've also been thinking of redoing it like this https://www.snellman.net/blog/archive/2016-12-13-ring-buffers/

**Comment by lust4life** [comment]
@haf   maybe it can redo like this ? #3  , 

p.s.  nice article use unsigned integer overflow and bitwise `&` for mask
